function nodejsLibs(prefix) {
  return {
    assert                : prefix + encodeURI(require.resolve('assert/')),
    buffer                : prefix + encodeURI(require.resolve('buffer/')),
    Buffer                : prefix + encodeURI(require.resolve('buffer/')),
    cluster               : null,
    console               : prefix + encodeURI(require.resolve('console-browserify')),
    constants             : prefix + encodeURI(require.resolve('constants-browserify')),
    crypto                : prefix + encodeURI(require.resolve('crypto-browserify')),
    dgram                 : null,
    dns                   : null,
    domain                : prefix + encodeURI(require.resolve('domain-browser')),
    events                : prefix + encodeURI(require.resolve('events/')),
    fs                    : null,
    http                  : prefix + encodeURI(require.resolve('stream-http')),
    https                 : prefix + encodeURI(require.resolve('https-browserify')),
    module                : null,
    net                   : null,
    os                    : prefix + encodeURI(require.resolve('os-browserify/browser.js')),
    path                  : prefix + encodeURI(require.resolve('path-browserify')),
    punycode              : prefix + encodeURI(require.resolve('punycode/')),
    process               : prefix + encodeURI(require.resolve('process/browser.js')),
    querystring           : prefix + encodeURI(require.resolve('querystring-es3/')),
    readline              : null,
    repl                  : null,
    stream                : prefix + encodeURI(require.resolve('stream-browserify')),
    _stream_duplex        : prefix + encodeURI(require.resolve('readable-stream/duplex.js')),
    _stream_passthrough   : prefix + encodeURI(require.resolve('readable-stream/passthrough.js')),
    _stream_readable      : prefix + encodeURI(require.resolve('readable-stream/readable.js')),
    _stream_transform     : prefix + encodeURI(require.resolve('readable-stream/transform.js')),
    _stream_writable      : prefix + encodeURI(require.resolve('readable-stream/writable.js')),
    string_decoder        : prefix + encodeURI(require.resolve('string_decoder/')),
    sys                   : prefix + encodeURI(require.resolve('util/util.js')),
    timers                : prefix + encodeURI(require.resolve('timers-browserify')),
    tls                   : null,
    tty                   : prefix + encodeURI(require.resolve('tty-browserify')),
    url                   : prefix + encodeURI(require.resolve('url/')),
    util                  : prefix + encodeURI(require.resolve('util/util.js')),
    vm                    : prefix + encodeURI(require.resolve('vm-browserify')),
    zlib                  : prefix + encodeURI(require.resolve('browserify-zlib')),
    empty                 : prefix + encodeURI(require.resolve('./shim/empty.js')),
  }
}

module.exports = nodejsLibs;
