function nodejsLibs(prefix) {
  return {
    assert                : prefix + require.resolve('assert/'),
    buffer                : prefix + require.resolve('buffer/'),
    Buffer                : prefix + require.resolve('buffer/'),
    cluster               : null,
    console               : prefix + require.resolve('console-browserify'),
    constants             : prefix + require.resolve('constants-browserify'),
    crypto                : prefix + require.resolve('crypto-browserify'),
    dgram                 : null,
    dns                   : null,
    domain                : prefix + require.resolve('domain-browser'),
    events                : prefix + require.resolve('events/'),
    fs                    : null,
    http                  : prefix + require.resolve('stream-http'),
    https                 : prefix + require.resolve('https-browserify'),
    module                : null,
    net                   : null,
    os                    : prefix + require.resolve('os-browserify/browser.js'),
    path                  : prefix + require.resolve('path-browserify'),
    punycode              : prefix + require.resolve('punycode/'),
    process               : prefix + require.resolve('process/browser.js'),
    querystring           : prefix + require.resolve('querystring-es3/'),
    readline              : null,
    repl                  : null,
    stream                : prefix + require.resolve('stream-browserify'),
    _stream_duplex        : prefix + require.resolve('readable-stream/duplex.js'),
    _stream_passthrough   : prefix + require.resolve('readable-stream/passthrough.js'),
    _stream_readable      : prefix + require.resolve('readable-stream/readable.js'),
    _stream_transform     : prefix + require.resolve('readable-stream/transform.js'),
    _stream_writable      : prefix + require.resolve('readable-stream/writable.js'),
    string_decoder        : prefix + require.resolve('string_decoder/'),
    sys                   : prefix + require.resolve('util/util.js'),
    timers                : prefix + require.resolve('timers-browserify'),
    tls                   : null,
    tty                   : prefix + require.resolve('tty-browserify'),
    url                   : prefix + require.resolve('url/'),
    util                  : prefix + require.resolve('util/util.js'),
    vm                    : prefix + require.resolve('vm-browserify'),
    zlib                  : prefix + require.resolve('browserify-zlib'),
    empty                 : prefix + require.resolve('./shim/empty.js'),
  }
}

module.exports = nodejsLibs;
